/**
 * Vector clock for causal ordering across locations.
 * Each entry maps a locationId to its logical counter.
 */
export interface VectorClock {
  [locationId: string]: number;
}

/**
 * Status lifecycle of an Operation_Envelope.
 */
export type EnvelopeStatus = 'pending' | 'syncing' | 'acknowledged' | 'failed';

/**
 * Supported operation types for offline mutations.
 */
export type OperationType =
  | 'pos_transaction'
  | 'inventory_adjustment'
  | 'stock_movement'
  | 'stock_deduction'
  | 'price_update'
  | 'customer_update';

/**
 * Client-side Operation_Envelope stored in IndexedDB.
 * Contains the full operation payload, tenant context, and sync metadata.
 */
export interface OperationEnvelope {
  /** UUID v4 */
  id: string;
  /** Unique per operation — used for exactly-once delivery */
  idempotencyKey: string;
  tenantId: string;
  branchId: string;
  locationId: string;
  /** Monotonic per offline session, starting at 1 */
  sequenceNumber: number;
  /** Offline session identifier */
  sessionId: string;
  /** ISO 8601 from client clock */
  timestamp: string;
  /** Causal ordering */
  vectorClock: VectorClock;
  operationType: OperationType;
  payload: Record<string, unknown>;
  status: EnvelopeStatus;
  retryCount: number;
  createdAt: string;
  /** AES-GCM encrypted form (optional) */
  encryptedPayload?: ArrayBuffer;
}

/**
 * Configuration for the Offline Store (IndexedDB layer).
 */
export interface OfflineStoreConfig {
  tenantId: string;
  branchId: string;
  locationId: string;
  /** Maximum pending operations before lockout. Default: 500, range: 100-2000 */
  offlineToleranceThreshold: number;
  /** Days to retain acknowledged operations before purge. Default: 7 */
  retentionDays: number;
}

/**
 * Report generated by the integrity verification on application startup.
 */
export interface IntegrityReport {
  totalEnvelopes: number;
  validEnvelopes: number;
  corruptEnvelopes: number;
  recoveredEnvelopes: number;
  orphanedEntries: number;
}

/**
 * Result of a cache read operation indicating whether the data was found
 * and its freshness status.
 */
export interface CacheReadResult<T = Record<string, unknown>> {
  /** The record data, or null if cache miss */
  data: T | null;
  /** Whether the result came from local (unacknowledged) modifications */
  isLocalModification: boolean;
  /** Whether the cached data is stale (from a previous sync cycle) */
  isStale: boolean;
  /** ISO timestamp of last successful cache sync, if available */
  lastSyncTimestamp: string | null;
}

/**
 * Metadata stored for cache sync tracking.
 */
export interface CacheMetadata {
  key: string;
  value: unknown;
  updatedAt: string;
}

/**
 * Options for delta sync configuration.
 */
export interface DeltaSyncOptions {
  /** Fetch function that retrieves changed records since a given timestamp */
  fetchChangedProducts?: (since: string | null) => Promise<Record<string, unknown>[]>;
  fetchChangedPrices?: (since: string | null) => Promise<Record<string, unknown>[]>;
  fetchChangedCustomers?: (since: string | null) => Promise<Record<string, unknown>[]>;
}

/**
 * Result of a delta sync operation.
 */
export interface DeltaSyncResult {
  productsUpdated: number;
  pricesUpdated: number;
  customersUpdated: number;
  syncTimestamp: string;
  isStale: boolean;
  error?: string;
}
