/**
 * Vector clock for causal ordering across locations.
 * Each entry maps a locationId to its logical counter.
 */
export interface VectorClock {
  [locationId: string]: number;
}

/**
 * Status lifecycle of an Operation_Envelope.
 */
export type EnvelopeStatus = 'pending' | 'syncing' | 'acknowledged' | 'failed';

/**
 * Supported operation types for offline mutations.
 */
export type OperationType =
  | 'pos_transaction'
  | 'inventory_adjustment'
  | 'stock_movement'
  | 'stock_deduction'
  | 'price_update'
  | 'customer_update';

/**
 * Client-side Operation_Envelope stored in IndexedDB.
 * Contains the full operation payload, tenant context, and sync metadata.
 */
export interface OperationEnvelope {
  /** UUID v4 */
  id: string;
  /** Unique per operation — used for exactly-once delivery */
  idempotencyKey: string;
  tenantId: string;
  branchId: string;
  locationId: string;
  /** Monotonic per offline session, starting at 1 */
  sequenceNumber: number;
  /** Offline session identifier */
  sessionId: string;
  /** ISO 8601 from client clock */
  timestamp: string;
  /** Causal ordering */
  vectorClock: VectorClock;
  operationType: OperationType;
  payload: Record<string, unknown>;
  status: EnvelopeStatus;
  retryCount: number;
  createdAt: string;
  /** AES-GCM encrypted form (optional) */
  encryptedPayload?: ArrayBuffer;
}

/**
 * Configuration for the Offline Store (IndexedDB layer).
 */
export interface OfflineStoreConfig {
  tenantId: string;
  branchId: string;
  locationId: string;
  /** Maximum pending operations before lockout. Default: 500, range: 100-2000 */
  offlineToleranceThreshold: number;
  /** Days to retain acknowledged operations before purge. Default: 7 */
  retentionDays: number;
}

/**
 * Report generated by the integrity verification on application startup.
 */
export interface IntegrityReport {
  totalEnvelopes: number;
  validEnvelopes: number;
  corruptEnvelopes: number;
  recoveredEnvelopes: number;
  orphanedEntries: number;
}
